// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: TickReqParams.proto
// Protobuf Java Version: 4.29.3

package com.ib.client.protobuf;

public final class TickReqParamsProto {
  private TickReqParamsProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      TickReqParamsProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TickReqParamsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.TickReqParams)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 reqId = 1;</code>
     * @return Whether the reqId field is set.
     */
    boolean hasReqId();
    /**
     * <code>optional int32 reqId = 1;</code>
     * @return The reqId.
     */
    int getReqId();

    /**
     * <code>optional string minTick = 2;</code>
     * @return Whether the minTick field is set.
     */
    boolean hasMinTick();
    /**
     * <code>optional string minTick = 2;</code>
     * @return The minTick.
     */
    java.lang.String getMinTick();
    /**
     * <code>optional string minTick = 2;</code>
     * @return The bytes for minTick.
     */
    com.google.protobuf.ByteString
        getMinTickBytes();

    /**
     * <code>optional string bboExchange = 3;</code>
     * @return Whether the bboExchange field is set.
     */
    boolean hasBboExchange();
    /**
     * <code>optional string bboExchange = 3;</code>
     * @return The bboExchange.
     */
    java.lang.String getBboExchange();
    /**
     * <code>optional string bboExchange = 3;</code>
     * @return The bytes for bboExchange.
     */
    com.google.protobuf.ByteString
        getBboExchangeBytes();

    /**
     * <code>optional int32 snapshotPermissions = 4;</code>
     * @return Whether the snapshotPermissions field is set.
     */
    boolean hasSnapshotPermissions();
    /**
     * <code>optional int32 snapshotPermissions = 4;</code>
     * @return The snapshotPermissions.
     */
    int getSnapshotPermissions();
  }
  /**
   * Protobuf type {@code protobuf.TickReqParams}
   */
  public static final class TickReqParams extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.TickReqParams)
      TickReqParamsOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        TickReqParams.class.getName());
    }
    // Use TickReqParams.newBuilder() to construct.
    private TickReqParams(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TickReqParams() {
      minTick_ = "";
      bboExchange_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ib.client.protobuf.TickReqParamsProto.internal_static_protobuf_TickReqParams_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ib.client.protobuf.TickReqParamsProto.internal_static_protobuf_TickReqParams_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ib.client.protobuf.TickReqParamsProto.TickReqParams.class, com.ib.client.protobuf.TickReqParamsProto.TickReqParams.Builder.class);
    }

    private int bitField0_;
    public static final int REQID_FIELD_NUMBER = 1;
    private int reqId_ = 0;
    /**
     * <code>optional int32 reqId = 1;</code>
     * @return Whether the reqId field is set.
     */
    @java.lang.Override
    public boolean hasReqId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 reqId = 1;</code>
     * @return The reqId.
     */
    @java.lang.Override
    public int getReqId() {
      return reqId_;
    }

    public static final int MINTICK_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object minTick_ = "";
    /**
     * <code>optional string minTick = 2;</code>
     * @return Whether the minTick field is set.
     */
    @java.lang.Override
    public boolean hasMinTick() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string minTick = 2;</code>
     * @return The minTick.
     */
    @java.lang.Override
    public java.lang.String getMinTick() {
      java.lang.Object ref = minTick_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        minTick_ = s;
        return s;
      }
    }
    /**
     * <code>optional string minTick = 2;</code>
     * @return The bytes for minTick.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMinTickBytes() {
      java.lang.Object ref = minTick_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        minTick_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BBOEXCHANGE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object bboExchange_ = "";
    /**
     * <code>optional string bboExchange = 3;</code>
     * @return Whether the bboExchange field is set.
     */
    @java.lang.Override
    public boolean hasBboExchange() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string bboExchange = 3;</code>
     * @return The bboExchange.
     */
    @java.lang.Override
    public java.lang.String getBboExchange() {
      java.lang.Object ref = bboExchange_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bboExchange_ = s;
        return s;
      }
    }
    /**
     * <code>optional string bboExchange = 3;</code>
     * @return The bytes for bboExchange.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBboExchangeBytes() {
      java.lang.Object ref = bboExchange_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bboExchange_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SNAPSHOTPERMISSIONS_FIELD_NUMBER = 4;
    private int snapshotPermissions_ = 0;
    /**
     * <code>optional int32 snapshotPermissions = 4;</code>
     * @return Whether the snapshotPermissions field is set.
     */
    @java.lang.Override
    public boolean hasSnapshotPermissions() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 snapshotPermissions = 4;</code>
     * @return The snapshotPermissions.
     */
    @java.lang.Override
    public int getSnapshotPermissions() {
      return snapshotPermissions_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, reqId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, minTick_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, bboExchange_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, snapshotPermissions_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, reqId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, minTick_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, bboExchange_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, snapshotPermissions_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ib.client.protobuf.TickReqParamsProto.TickReqParams)) {
        return super.equals(obj);
      }
      com.ib.client.protobuf.TickReqParamsProto.TickReqParams other = (com.ib.client.protobuf.TickReqParamsProto.TickReqParams) obj;

      if (hasReqId() != other.hasReqId()) return false;
      if (hasReqId()) {
        if (getReqId()
            != other.getReqId()) return false;
      }
      if (hasMinTick() != other.hasMinTick()) return false;
      if (hasMinTick()) {
        if (!getMinTick()
            .equals(other.getMinTick())) return false;
      }
      if (hasBboExchange() != other.hasBboExchange()) return false;
      if (hasBboExchange()) {
        if (!getBboExchange()
            .equals(other.getBboExchange())) return false;
      }
      if (hasSnapshotPermissions() != other.hasSnapshotPermissions()) return false;
      if (hasSnapshotPermissions()) {
        if (getSnapshotPermissions()
            != other.getSnapshotPermissions()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasReqId()) {
        hash = (37 * hash) + REQID_FIELD_NUMBER;
        hash = (53 * hash) + getReqId();
      }
      if (hasMinTick()) {
        hash = (37 * hash) + MINTICK_FIELD_NUMBER;
        hash = (53 * hash) + getMinTick().hashCode();
      }
      if (hasBboExchange()) {
        hash = (37 * hash) + BBOEXCHANGE_FIELD_NUMBER;
        hash = (53 * hash) + getBboExchange().hashCode();
      }
      if (hasSnapshotPermissions()) {
        hash = (37 * hash) + SNAPSHOTPERMISSIONS_FIELD_NUMBER;
        hash = (53 * hash) + getSnapshotPermissions();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ib.client.protobuf.TickReqParamsProto.TickReqParams parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ib.client.protobuf.TickReqParamsProto.TickReqParams parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ib.client.protobuf.TickReqParamsProto.TickReqParams parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ib.client.protobuf.TickReqParamsProto.TickReqParams parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ib.client.protobuf.TickReqParamsProto.TickReqParams parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ib.client.protobuf.TickReqParamsProto.TickReqParams parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ib.client.protobuf.TickReqParamsProto.TickReqParams parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.ib.client.protobuf.TickReqParamsProto.TickReqParams parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.ib.client.protobuf.TickReqParamsProto.TickReqParams parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.ib.client.protobuf.TickReqParamsProto.TickReqParams parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ib.client.protobuf.TickReqParamsProto.TickReqParams parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.ib.client.protobuf.TickReqParamsProto.TickReqParams parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ib.client.protobuf.TickReqParamsProto.TickReqParams prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.TickReqParams}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.TickReqParams)
        com.ib.client.protobuf.TickReqParamsProto.TickReqParamsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ib.client.protobuf.TickReqParamsProto.internal_static_protobuf_TickReqParams_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ib.client.protobuf.TickReqParamsProto.internal_static_protobuf_TickReqParams_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ib.client.protobuf.TickReqParamsProto.TickReqParams.class, com.ib.client.protobuf.TickReqParamsProto.TickReqParams.Builder.class);
      }

      // Construct using com.ib.client.protobuf.TickReqParamsProto.TickReqParams.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        reqId_ = 0;
        minTick_ = "";
        bboExchange_ = "";
        snapshotPermissions_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ib.client.protobuf.TickReqParamsProto.internal_static_protobuf_TickReqParams_descriptor;
      }

      @java.lang.Override
      public com.ib.client.protobuf.TickReqParamsProto.TickReqParams getDefaultInstanceForType() {
        return com.ib.client.protobuf.TickReqParamsProto.TickReqParams.getDefaultInstance();
      }

      @java.lang.Override
      public com.ib.client.protobuf.TickReqParamsProto.TickReqParams build() {
        com.ib.client.protobuf.TickReqParamsProto.TickReqParams result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ib.client.protobuf.TickReqParamsProto.TickReqParams buildPartial() {
        com.ib.client.protobuf.TickReqParamsProto.TickReqParams result = new com.ib.client.protobuf.TickReqParamsProto.TickReqParams(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.ib.client.protobuf.TickReqParamsProto.TickReqParams result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.reqId_ = reqId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.minTick_ = minTick_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.bboExchange_ = bboExchange_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.snapshotPermissions_ = snapshotPermissions_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ib.client.protobuf.TickReqParamsProto.TickReqParams) {
          return mergeFrom((com.ib.client.protobuf.TickReqParamsProto.TickReqParams)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ib.client.protobuf.TickReqParamsProto.TickReqParams other) {
        if (other == com.ib.client.protobuf.TickReqParamsProto.TickReqParams.getDefaultInstance()) return this;
        if (other.hasReqId()) {
          setReqId(other.getReqId());
        }
        if (other.hasMinTick()) {
          minTick_ = other.minTick_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasBboExchange()) {
          bboExchange_ = other.bboExchange_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasSnapshotPermissions()) {
          setSnapshotPermissions(other.getSnapshotPermissions());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                reqId_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                minTick_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                bboExchange_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                snapshotPermissions_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int reqId_ ;
      /**
       * <code>optional int32 reqId = 1;</code>
       * @return Whether the reqId field is set.
       */
      @java.lang.Override
      public boolean hasReqId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 reqId = 1;</code>
       * @return The reqId.
       */
      @java.lang.Override
      public int getReqId() {
        return reqId_;
      }
      /**
       * <code>optional int32 reqId = 1;</code>
       * @param value The reqId to set.
       * @return This builder for chaining.
       */
      public Builder setReqId(int value) {

        reqId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 reqId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearReqId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        reqId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object minTick_ = "";
      /**
       * <code>optional string minTick = 2;</code>
       * @return Whether the minTick field is set.
       */
      public boolean hasMinTick() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string minTick = 2;</code>
       * @return The minTick.
       */
      public java.lang.String getMinTick() {
        java.lang.Object ref = minTick_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          minTick_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string minTick = 2;</code>
       * @return The bytes for minTick.
       */
      public com.google.protobuf.ByteString
          getMinTickBytes() {
        java.lang.Object ref = minTick_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          minTick_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string minTick = 2;</code>
       * @param value The minTick to set.
       * @return This builder for chaining.
       */
      public Builder setMinTick(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        minTick_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string minTick = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMinTick() {
        minTick_ = getDefaultInstance().getMinTick();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string minTick = 2;</code>
       * @param value The bytes for minTick to set.
       * @return This builder for chaining.
       */
      public Builder setMinTickBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        minTick_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object bboExchange_ = "";
      /**
       * <code>optional string bboExchange = 3;</code>
       * @return Whether the bboExchange field is set.
       */
      public boolean hasBboExchange() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string bboExchange = 3;</code>
       * @return The bboExchange.
       */
      public java.lang.String getBboExchange() {
        java.lang.Object ref = bboExchange_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bboExchange_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string bboExchange = 3;</code>
       * @return The bytes for bboExchange.
       */
      public com.google.protobuf.ByteString
          getBboExchangeBytes() {
        java.lang.Object ref = bboExchange_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bboExchange_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string bboExchange = 3;</code>
       * @param value The bboExchange to set.
       * @return This builder for chaining.
       */
      public Builder setBboExchange(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        bboExchange_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional string bboExchange = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBboExchange() {
        bboExchange_ = getDefaultInstance().getBboExchange();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>optional string bboExchange = 3;</code>
       * @param value The bytes for bboExchange to set.
       * @return This builder for chaining.
       */
      public Builder setBboExchangeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        bboExchange_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private int snapshotPermissions_ ;
      /**
       * <code>optional int32 snapshotPermissions = 4;</code>
       * @return Whether the snapshotPermissions field is set.
       */
      @java.lang.Override
      public boolean hasSnapshotPermissions() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional int32 snapshotPermissions = 4;</code>
       * @return The snapshotPermissions.
       */
      @java.lang.Override
      public int getSnapshotPermissions() {
        return snapshotPermissions_;
      }
      /**
       * <code>optional int32 snapshotPermissions = 4;</code>
       * @param value The snapshotPermissions to set.
       * @return This builder for chaining.
       */
      public Builder setSnapshotPermissions(int value) {

        snapshotPermissions_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 snapshotPermissions = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSnapshotPermissions() {
        bitField0_ = (bitField0_ & ~0x00000008);
        snapshotPermissions_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.TickReqParams)
    }

    // @@protoc_insertion_point(class_scope:protobuf.TickReqParams)
    private static final com.ib.client.protobuf.TickReqParamsProto.TickReqParams DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ib.client.protobuf.TickReqParamsProto.TickReqParams();
    }

    public static com.ib.client.protobuf.TickReqParamsProto.TickReqParams getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TickReqParams>
        PARSER = new com.google.protobuf.AbstractParser<TickReqParams>() {
      @java.lang.Override
      public TickReqParams parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TickReqParams> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TickReqParams> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ib.client.protobuf.TickReqParamsProto.TickReqParams getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_TickReqParams_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_TickReqParams_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023TickReqParams.proto\022\010protobuf\"\263\001\n\rTick" +
      "ReqParams\022\022\n\005reqId\030\001 \001(\005H\000\210\001\001\022\024\n\007minTick" +
      "\030\002 \001(\tH\001\210\001\001\022\030\n\013bboExchange\030\003 \001(\tH\002\210\001\001\022 \n" +
      "\023snapshotPermissions\030\004 \001(\005H\003\210\001\001B\010\n\006_reqI" +
      "dB\n\n\010_minTickB\016\n\014_bboExchangeB\026\n\024_snapsh" +
      "otPermissionsB=\n\026com.ib.client.protobufB" +
      "\022TickReqParamsProto\252\002\016IBApi.protobufb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protobuf_TickReqParams_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_TickReqParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_TickReqParams_descriptor,
        new java.lang.String[] { "ReqId", "MinTick", "BboExchange", "SnapshotPermissions", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
